### ISSUE TITLE
签到全都失败了

### ISSUE THREAD

**Issue by madlight-du** [kookxiang/Tieba_Sign-Go#1]
机器：win8.1 X64   程序：Tieba_Sign-Go.x64
所有签到都失败了，自己建的cookie.txt。还有就是用程序登录怎么都显示登录错误 代码是-257 ，

**Comment by kookxiang** [comment]
推荐用 cookie 方式，因为登录逻辑百度改了很多次。
你这个 cookie 换行方式切成 linux 换行就好了，我到时候兼容下

**Comment by madlight-du** [comment]
请教一下怎么用linux方式换行，我用\n换行提示加载cookie失败
![image](https://cloud.githubusercontent.com/assets/3970620/15592836/929c7d14-23d9-11e6-8c4e-4cd479875938.png)

**Comment by kookxiang** [comment]
https://github.com/kookxiang/Tieba_Sign-Go/releases/tag/0.2.1
试试这个版本解决了吗

**Comment by madlight-du** [comment]
0.2.1版本已经解决，签到已经成功了，不过我发现了一个可以优化一下的地方，就是增加一个检测机制，发现签到的贴吧列表里面有已经被删除的贴吧不做重试签到。

**Comment by kookxiang** [comment]
指的是被封的贴吧吧，下一步会考虑处理
