### ISSUE TITLE
话说新更新的Tieba_Sign怎么搭建了

### ISSUE THREAD

**Issue by iikira** [kookxiang/Tieba_Sign-Go#5]
Tieba_Sign常规安装了一遍，进入主页，发现登不进去，老提示<对不起，您的用户名或密码错误，无法登录.>（保证没输错密码）
重试了好多遍了
然后看了说明:<这份代码不能直接部署到服务器上，因为还需要一个 Go 语言的服务端程序才可以正常运行（不开源）。>
不知是否与这个有关。
还有那啥服务端程序，是不是将这个Tieba_Sign-Go.linux.amd64.bin文件放在网站的根目录下，或者放哪里，怎么部署，不太懂。

**Comment by kookxiang** [comment]
1. 跟本项目无关
2. 已经说明是闭源项目了，不是你能下载到的
