### ISSUE TITLE
提优化建议。。

### ISSUE THREAD

**Issue by iikira** [kookxiang/Tieba_Sign-Go#6]
贴吧签到基本没问题。

> 多用户模式下可指定导入cookie的文件夹
> 输出签到错误信息到日志文件里面
> 检测全吧封禁。。。
> 作者dd回复真快。好评。

**Comment by kookxiang** [comment]
1. 不知道有什么意义，实在不行 `ln -s` 也能解决问题
2. `grep` 命令过滤下就行，没必要内置进去
3. 从没被封过，所以没法做

**Comment by iikira** [comment]
第一个想到解决办法了。
第二个额没说清楚，第二条指的是输出签到失败的原因，比如用户未登录，已被拉黑，签到太快看看帖子再来，根据相关法律法规等等
第三个，只是想把 被全吧封禁的号删掉，我好多号都被封了。。可以的话我提供几个、。

**Comment by kookxiang** [comment]
你可以用 grep 命令过滤输出，另外就算被封禁了也只是多重试几次吧，没见到有什么不良影响

**Comment by iikira** [comment]
好吧，我先用用看
