### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by iikira** [kookxiang/Tieba_Sign-Go#7]
最近把这个弄到 虚拟主机 上。虚拟主机成本低，很多服务商支持免费，然后……出现了这些问题：

> bduss数据 存在泄露的风险
> 某些坑爹的服务商不允许虚拟主机放置签到站，屏蔽了签到的那个地址。。

所以希望加密bduss和签到地址……
另外，执行程序的时候直接带上bduss信息就好了，弄cookie文件太烦……
不知作者有什么想法

**Comment by kookxiang** [comment]
1. 签到需要使用，肯定是需要解密的，然后解密算法和解密密钥都在的情况下跟明文也没区别
2. 屏蔽了自己找提供商
