### ISSUE TITLE
疑似bug

### ISSUE THREAD

**Issue by iikira** [kookxiang/Tieba_Sign-Go#9]
帐号关注上千(2003)个贴吧，使用此程序签到贴吧时，会有重复签到，循环列表签到的情况，程序就不会自动结束了
少量贴吧则没事

**Comment by kookxiang** [comment]
签到失败会自动加到队列尾部，到了一定重试次数会自动结束

**Comment by iikira** [comment]
签到都显示成功了阿，你看下日志吧，[http://104.130.0.114/130.txt](http://104.130.0.114/130.txt)

**Comment by iikira** [comment]
找到原因了，这个获取贴吧列表的接口http://tieba.baidu.com/f/like/mylike?&pn=
pn的值一旦超过101就会重定向到pn＝1
更换客户端接口吧

**Comment by kookxiang** [comment]
按照百度贴吧的规定，最多只能关注 2000 个贴吧，折算下来最多 100 页
另外我记得客户端接口限制更多吧

**Comment by iikira** [comment]
现在最多3001
客户端确实能获取

**Comment by iikira** [comment]
时间过的真快，作者还是没有更新。
于是我写了个php示例（不懂go），看看怎么样
优化代码...

``` php
<?php
                $pn=495;//页数
                $BDUSS='';//optional
                $str = 'BDUSS='.$BDUSS.'&_client_version=6.9.2.1&page_no='.$pn.'&page_size=200&uid='.$uid;
                $r = file_get_contents('http://c.tieba.baidu.com/c/f/forum/like?'.$str.'&sign='.strtoupper(md5(str_replace('&','',$str).'tiebaclient!!!')));
                echo '<meta charset=utf-8><pre>';
                print_r( json_decode($r));
?></pre>
```

**Comment by kookxiang** [comment]
请不要再公开场合发布 BDUSS，已代修改
因为最近在忙别的项目，没有时间重写这块的代码

**Comment by iikira** [comment]
我已经重写抓取贴吧列表的代码，可以pull了吗
其它某些文件的代码也要一起改
